import Link from "next/link"
import { MainNav } from "@/components/main-nav"
import { Gallery } from "@/components/gallery"

// This is now a static object instead of a function
const sections = [
  { id: 1, title: "Supplicié-vitrail	et	Vitraux", description: "The formative years of artistic exploration." },
  { id: 2, title: "Période	Brune", description: "A journey into non-representational art." },
  { id: 3, title: "Du Bouquet Rose au Rouge", description: "Inspired by the beauty of the natural world." },
  { id: 4, title: "La	Révolte...	aux	Eglises-femme", description: "Capturing the essence of city life." },
  { id: 5, title: "Notables", description: "Exploring the human form and expression." },
  { id: 6, title: "Visages	vers	le	Ciel", description: "Pushing the boundaries of conventional art." },
  { id: 7, title: "Masques", description: "Three-dimensional explorations of form." },
  { id: 8, title: "Couples	de	la	Passion		Femmes	aux	Seins", description: "Embracing technology in artistic expression." },
  { id: 9, title: "Suppliciés	'Je	les	peignais	en	alternance	avec	les	Couples.'	MR", description: "Works created with fellow artists." },
  { id: 10, title: "Suppliciées	Ange	Noir	Couples	des	Cendres...	au	Supplicié-vitrail", description: "The latest creations and ongoing projects." },
]

// This is now a static object with artworks for each section
const artworksPerSection = {
  "1": [
    {
      id: 1,
      title: "SUPPLICIE 125 1992 116x89",
      description: "Au rasoir... supplicié-vitrail. \"La matière s'élime, épuisée,... déserte son faciès... Exsangue, de moins en moins lisible, il affleure, relique estampillée dans le linceuil de la toile. Alors le peintre parvient à mettre au jour sa lumière la plus enfouie. Car l'éternité ne se découvre qu'en s'approchant de ce qu'il y a de plus vivant.\" - Nathalie Cottin Ayache",
      image: "/rubriques/one/1SUPPLICIE.jpg",
    },
    {
      id: 2,
      title: "SUPPLICIE 142 1994 100x81",
      description: "",
      image: "/rubriques/one/1_2SUPPLICIE.jpg",
    },
    {
      id: 3,
      title: "VITRAIL WIMEREUX 1958 ST JEAN MARIE VIANNEY",
      description: "LA LUMIÈRE, JOYEUX et TENDRE",
      image: "/rubriques/one/1_3VITRAIL.jpg",
    },
    {
      id: 4,
      title: "VITRAIL WIMEREUX EGLISE IMMACULEE CONCEPTION",
      description: "",
      image: "/rubriques/one/1_4VITRAIL.jpg",
    },
    {
      id: 5,
      title: "VITRAIL WIMEREUX",
      description: "",
      image: "/rubriques/one/1_5VITRAIL.jpg",
    },
    {
      id: 6,
      title: "VITRAIL WIMEREUX",
      description: "",
      image: "/rubriques/one/1_6VITRAIL.jpg",
    },
    {
      id: 7,
      title: "VITRAIL WIMEREUX",
      description: "",
      image: "/rubriques/one/1_7VITRAIL.jpg",
    },
    {
      id: 8,
      title: "CROQUIS FUSAIN VIERGE de GUERNES 1954 58 150x65",
      description: "Maurice Rocher a fait des vitraux de 1946 à 1966.",
      image: "/rubriques/one/1_8CROQUIS.jpg",
    },
    {
      id: 9,
      title: "EGLISE NOTRE DAME DE GUERNES",
      description: "",
      image: "/rubriques/one/1_9EGLISE.jpg",
    },
    {
      id: 10,
      title: "MAQUETTE VITRAUX GUADALAJARA TEMPLO EXPIATORIO 1966 85",
      description: "",
      image: "/rubriques/one/2_1MAQUETTE.jpg",
    },
    {
      id: 11,
      title: "VITRAUX GUADALAJARA 1966 85",
      description: "",
      image: "/rubriques/one/2_2VITRAUX.jpg",
    },
    {
      id: 12,
      title: "VITRAUX GUADALAJARA 1966 85",
      description: "",
      image: "/rubriques/one/2_3GUADALAJARA.jpg",
    },
    {
      id: 13,
      title: "BASILIQUE d EVRON 1951",
      description: "",
      image: "/rubriques/one/2_4BASILIQUE.jpg",
    },
    {
      id: 14,
      title: "LES SAINTS EGLISE SAINT LOUIS BREST 1959",
      description: "",
      image: "/rubriques/one/2_5_LES_SAINTS.jpg",
    },
    {
      id: 15,
      title: "EGLISE-NOTRE DAME de CAVIGNY 1961",
      description: "",
      image: "/rubriques/one/2_6EGLISE.jpg",
    },
    {
      id: 16,
      title: "CHAPELLE du JUVENAT CHATEAULIN 1963",
      description: "",
      image: "/rubriques/one/2_7CHAPELLE.jpg",
    },
    {
      id: 17,
      title: "EGLISE NOTRE-DAME- DE-TOUTES-AIDES NANTES 1958",
      description: "",
      image: "/rubriques/one/2_8EGLISE.jpg",
    },
    {
      id: 18,
      title: "au CENTRE d ART SACRE 1948 avec G. Desvallières et J. Pichard",
      description: "MR a été aux Ateliers d'art sacré avec Maurice Denis et Georges Desvallières. \"Ce que m'apportait Denis sur le plan plastique, Desvallières me l'apportait sur le plan spirituel.\" - MR",
      image: "/rubriques/one/2_9CENTREdART.jpg",
    },
    {
      id: 19,
      title: "MAURICE ROCHER vers 1946 PEIGNANT 1 FRESQUE",
      description: "",
      image: "/rubriques/one/3_0MAURICEROCHER.jpg",
    },
    {
      id: 20,
      title: "FRESQUE Le VERBE et la PAROLE EGLISE ST DOMINIQUE PARIS 1946",
      description: "",
      image: "/rubriques/one/3_1FRESQUE.JPG",
    },
  ],
  "2": [
    {
      id: 1,
      title: "ÉTUDE EGLISE D’ÉVRON FONDS BAPTISMAUX, 1937-38",
      description: "Pendant 20 ans sa palette se limite à du noir et du brun.",
      image: "/rubriques/two/3_2.jpg",
    },
    {
      id: 2,
      title: "Geometric Harmony",
      description: "",
      image: "/rubriques/two/3_3.JPG",
    },
    {
      id: 3,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/3_4.JPG",
    },
    {
      id: 4,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/3_5.JPG",
    },
    {
      id: 5,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/3_6.jpg",
    },
    {
      id: 6,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/3_7.jpg",
    },
    {
      id: 7,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/3_8.JPG",
    },
    {
      id: 8,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/3_9.jpg",
    },
    {
      id: 9,
      title: "COUPLE, 1949 130x97",
      description: "Un voyage en Belgique lui fait découvrir le peintre expressionniste flamand Permek.",
      image: "/rubriques/two/4_0.jpg",
    },
    {
      id: 10,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_1.jpg",
    },
    {
      id: 11,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_2.jpg",
    },
    {
      id: 12,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_3.jpg",
    },
    {
      id: 13,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_4.jpg",
    },
    {
      id: 14,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_5.jpg",
    },
    {
      id: 15,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_6.jpg",
    },
    {
      id: 16,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_7.jpg",
    },
    {
      id: 17,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_8.jpg",
    },
    {
      id: 18,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/4_9.jpg",
    },
    {
      id: 19,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_0.jpg",
    },
    {
      id: 20,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_1.jpg",
    },
    {
      id: 21,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_2.jpg",
    },
    {
      id: 22,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_3.jpg",
    },
    {
      id: 23,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_4.jpg",
    },
    {
      id: 24,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_5.jpg",
    },
    {
      id: 25,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_6.jpg",
    },
    {
      id: 26,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_7.jpg",
    },
    {
      id: 27,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_8.jpg",
    },
    {
      id: 28,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/5_9.jpg",
    },
    {
      id: 29,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_0.jpg",
    },
    {
      id: 30,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_1.jpg",
    },
    {
      id: 31,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_2.jpg",
    },
    {
      id: 32,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_3.jpg",
    },
    {
      id: 33,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_4.jpg",
    },
    {
      id: 34,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_5.jpg",
    },
    {
      id: 35,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_6.jpg",
    },
    {
      id: 36,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_7.jpg",
    },
    {
      id: 37,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_8.jpg",
    },
    {
      id: 38,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/6_9.jpg",
    },
    {
      id: 39,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_0.png",
    },
    {
      id: 40,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_1.jpg",
    },
    {
      id: 41,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_2.jpg",
    },
    {
      id: 42,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_3.jpg",
    },
    {
      id: 43,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_4.JPG",
    },
    {
      id: 44,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_5.JPG",
    },
    {
      id: 45,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_6.jpg",
    },
    {
      id: 46,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_7.jpg",
    },
    {
      id: 47,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_8.jpg",
    },
    {
      id: 48,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/7_9.jpg",
    },
    {
      id: 49,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/8_0.jpg",
    },
    {
      id: 50,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/8_1.JPG",
    },
    {
      id: 51,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/8_2.jpg",
    },
    {
      id: 52,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/8_3.jpg",
    },
    {
      id: 53,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/8_4.jpg",
    },
    {
      id: 54,
      title: "Emotional Abstractions",
      description: "",
      image: "/rubriques/two/8_5.jpg",
    },
  ],
  "3": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/8_6.JPG",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/8_7.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/8_8.jpg",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/8_9.jpg",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_0.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_1.jpg",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_2.jpg",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_3.JPG",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_4.JPG",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_5.jpg",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_6.jpg",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_7.JPG",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_8.JPG",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_8_2.JPG",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/9_9.JPG",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_0.JPG",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_1.JPG",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_2.JPG",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_3.JPG",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_4.jpg",
    },
    {
      id: 21,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_5.jpg",
    },
    {
      id: 22,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_6.jpg",
    },
    {
      id: 23,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_7.jpg",
    },
    {
      id: 24,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_8.jpg",
    },
    {
      id: 25,
      title: "Color Fields",
      description: "",
      image: "/rubriques/three/10_9.jpg",
    },
  ],
  "4": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_0.jpg",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_1.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_2.jpg",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_3.jpg",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_4.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_5.jpg",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_6.JPG",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_7.JPG",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_8.JPG",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/11_9.JPG",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_0.jpg",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_1.jpg",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_2.JPG",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_3.jpg",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_4.jpg",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_5.jpg",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_6.jpg",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_7.JPG",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_8.jpg",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/12_9.JPG",
    },
    {
      id: 21,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_0.jpg",
    },
    {
      id: 22,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_1.jpg",
    },
    {
      id: 23,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_2.JPG",
    },
    {
      id: 24,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_3.jpg",
    },
    {
      id: 25,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_4.jpg",
    },
    {
      id: 26,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_5.jpg",
    },
    {
      id: 27,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_6.jpg",
    },
    {
      id: 28,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_7.jpg",
    },
    {
      id: 29,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_8.jpg",
    },
    {
      id: 30,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/13_9.jpg",
    },
    {
      id: 31,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/14_0.jpg",
    },
    {
      id: 32,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/14_1.jpg",
    },
    {
      id: 33,
      title: "Color Fields",
      description: "",
      image: "/rubriques/four/14_2.jpg",
    },
  ],
  "5": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/14_3.jpg",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/14_4.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/14_5.jpg",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/14_6.jpg",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/14_7.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/14_8.jpg",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/14_9.jpg",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_0.jpg",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_1.jpg",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_2.jpg",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_3.jpg",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_4.jpg",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_5.jpg",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_6.jpg",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_7.jpg",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_8.jpg",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/15_9.jpg",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_0.jpg",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_1.jpg",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_2.jpg",
    },
    {
      id: 21,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_3.jpg",
    },
    {
      id: 22,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_4.jpg",
    },
    {
      id: 23,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_5.jpg",
    },
    {
      id: 24,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_6.jpg",
    },
    {
      id: 25,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_7.jpg",
    },
    {
      id: 26,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_8.jpg",
    },
    {
      id: 27,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/16_9.JPG",
    },
    {
      id: 28,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/17_0.jpg",
    },
    {
      id: 29,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/17_1.jpg",
    },
    {
      id: 30,
      title: "Color Fields",
      description: "",
      image: "/rubriques/five/17_2.JPG",
    },
  ],
  "6": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/17_3.jpg",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/17_4.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/17_5.jpg",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/17_6.JPG",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/17_7.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/17_8.JPG",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/17_9.jpg",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_0.JPG",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_1.JPG",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_2.JPG",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_3.JPG",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_4.JPG",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_5.JPG",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_6.JPG",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_7.jpg",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_8.JPG",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/18_9.JPG",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_0.JPG",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_1.JPG",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_2.JPG",
    },
    {
      id: 21,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_3.JPG",
    },
    {
      id: 22,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_4.JPG",
    },
    {
      id: 23,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_5.jpg",
    },
    {
      id: 24,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_6.JPG",
    },
    {
      id: 25,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_7.jpg",
    },
    {
      id: 26,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_8.jpg",
    },
    {
      id: 27,
      title: "Color Fields",
      description: "",
      image: "/rubriques/six/19_9.png",
    },
  ],
  "7": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_0.png",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_1.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_2.jpg",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_3.jpg",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_4.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_5.jpg",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_6.jpg",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_7.jpg",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_8.jpg",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/20_9.JPG",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_0.jpg",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_1.jpg",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_2.jpg",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_3.jpg",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_4.jpg",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_5.jpg",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_6.jpg",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_7.jpg",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_8.jpg",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/21_9.jpg",
    },
    {
      id: 21,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_0.jpg",
    },
    {
      id: 22,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_1.jpg",
    },
    {
      id: 23,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_2.jpg",
    },
    {
      id: 24,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_3.jpg",
    },
    {
      id: 25,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_4.jpg",
    },
    {
      id: 26,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_5.jpg",
    },
    {
      id: 27,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_6.jpg",
    },
    {
      id: 28,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_7.JPG",
    },
    {
      id: 29,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_8.jpg",
    },
    {
      id: 30,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_8_1.jpg",
    },
    {
      id: 31,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/22_9.jpg",
    },
    {
      id: 32,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_0.jpg",
    },
    {
      id: 33,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_1.jpg",
    },
    {
      id: 34,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_2.jpg",
    },
    {
      id: 35,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_3.jpg",
    },
    {
      id: 36,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_4.jpg",
    },
    {
      id: 37,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_5.jpg",
    },
    {
      id: 38,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_6.jpg",
    },
    {
      id: 39,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_7.jpg",
    },
    {
      id: 40,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_8.jpg",
    },
    {
      id: 41,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/23_9.JPG",
    },
    {
      id: 42,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/24_0.jpg",
    },
    {
      id: 43,
      title: "Color Fields",
      description: "",
      image: "/rubriques/seven/24_1.jpg",
    },
  ],
  "8": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_2.jpg",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_3.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_4.jpg",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_5.jpg",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_6.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_7.JPG",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_8.jpg",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/24_9.JPG",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_0.jpg",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_1.JPG",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_2.jpg",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_3.JPG",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_4.JPG",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_5.JPG",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_6.jpg",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_7.jpg",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_8.jpg",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/25_9.jpg",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/26_0.jpg",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/eight/26_1.JPG",
    },
  ],
  "9": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_2.jpg",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_3_0.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_3_2.jpg",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_4.JPG",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_5.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_6.jpg",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_7.jpg",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_8.jpg",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/26_9.jpg",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_0.jpg",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_1.jpg",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_2.jpg",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_3.jpg",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_4.jpg",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_5.jpg",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_6.jpg",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_7.jpg",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_8.jpg",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/27_9.jpg",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_0.jpg",
    },
    {
      id: 21,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_1.jpg",
    },
    {
      id: 22,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_2.jpg",
    },
    {
      id: 23,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_3.jpg",
    },
    {
      id: 24,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_4.JPG",
    },
    {
      id: 25,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_5.jpg",
    },
    {
      id: 26,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_6.jpg",
    },
    {
      id: 27,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_7.jpg",
    },
    {
      id: 28,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_8.jpg",
    },
    {
      id: 29,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/28_9.jpg",
    },
    {
      id: 30,
      title: "Color Fields",
      description: "",
      image: "/rubriques/nine/29_0.jpg",
    },
  ],
  "10": [
    {
      id: 1,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_1.jpg",
    },
    {
      id: 2,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_2.jpg",
    },
    {
      id: 3,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_3.bmp",
    },
    {
      id: 4,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_4.jpg",
    },
    {
      id: 5,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_5.jpg",
    },
    {
      id: 6,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_6.jpg",
    },
    {
      id: 7,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_7.JPG",
    },
    {
      id: 8,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_8.jpg",
    },
    {
      id: 9,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/29_9.jpg",
    },
    {
      id: 10,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_0.jpg",
    },
    {
      id: 11,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_1.jpg",
    },
    {
      id: 12,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_2.JPG",
    },
    {
      id: 13,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_3.jpg",
    },
    {
      id: 14,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_4.jpg",
    },
    {
      id: 15,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_5.jpg",
    },
    {
      id: 16,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_6.jpg",
    },
    {
      id: 17,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_7.jpg",
    },
    {
      id: 18,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_8.jpg",
    },
    {
      id: 19,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/30_9.jpg",
    },
    {
      id: 20,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_0.jpg",
    },
    {
      id: 21,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_1.JPG",
    },
    {
      id: 22,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_2.jpg",
    },
    {
      id: 23,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_3.jpg",
    },
    {
      id: 24,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_4.jpg",
    },
    {
      id: 25,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_5.JPG",
    },
    {
      id: 26,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_6.jpg",
    },
    {
      id: 27,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_7.jpg",
    },
    {
      id: 28,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_8.jpg",
    },
    {
      id: 29,
      title: "Color Fields",
      description: "",
      image: "/rubriques/ten/31_9.JPG",
    },
  ],
}
export default function SectionPage({ params }: { params: { id: string } }) {
  const section = sections.find((s) => s.id === Number.parseInt(params.id))
  const artworks = artworksPerSection[params.id as keyof typeof artworksPerSection] || []

  if (!section) {
    return <div>Section not found</div>
  }

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="pb-24">
        <div className="mb-8 p-8">
          <Link href="/oeuvre" className="mb-4 inline-block text-sm text-gray-400 hover:text-white">
            ← Back to Oeuvre
          </Link>
          <h1 className="mb-2 text-4xl font-light">{section.title}</h1>
          <p className="text-lg text-gray-300">{section.description}</p>
        </div>
        <Gallery artworks={artworks} />
      </div>
      <MainNav className="fixed bottom-0 left-0 right-0" />
    </main>
  )
}

